apiVersion: v1
kind: Pod
metadata:
  name: product-service-import 
spec:
  containers:
    - name: product-service-import 
      image: theburi/product-reviews-import 
      volumeMounts:
          - mountPath: "/cert"
            name: mdbuser-pem
            readOnly: true
      
  restartPolicy: Never
  volumes:
    - name: mdbuser-pem
      secret:
        secretName: product-svc-mdbuser-pem

