apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product-svc
  labels:
    component: product-svc
spec:
  replicas: 1 
  selector:
    matchLabels:
      component: product-svc   
  template:
    metadata:
      labels: # labels to select/identify the deployment
        component: product-svc  
    spec:     # pod spec               
      containers: 
      - name: product-svc
        image: quay.io/ansulliv/product_svc:0.1 # image Andrew placed on quay.io
        ports:
        - containerPort: 5274
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: product-svc-mdbuser-pem
                key: uri
        volumeMounts:
          - mountPath: "/cert"
            name: mdbuser-pem
            readOnly: true
      volumes:
        - name: mdbuser-pem
          secret:
            secretName: product-svc-mdbuser-pem
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    component: product-svc
spec:
  selector:
    component: product-svc
  ports:
  - name: http
    targetPort: 5274
    port: 80

