---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: product-service-2-mdb
spec:
  type: ReplicaSet

  members: 3
  version: 4.0.10

  project: configmap-opsmanager
  credentials: secret-opsmanager-credentials

  # look into `replica-set-persistent-volumes.yaml` for an example on how to use
  # Kubernetes Persistent Volumes in your MDB deployment.
  persistent: true
  podSpec:
    persistence:
      multiple:
        data:          
          storage: 10Gi        
        journal:          
          storage: 1Gi               
        logs:        
          storage: 500M
  #
  security:
    tls:
      enabled: true
    
    # clusterAuthenticationMode: x509
  


