---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: product-service-mdb
spec:
  type: ReplicaSet

  members: 3
  version: 4.0.9

  project: configmap-opsmanager
  credentials: secret-opsmanager-credentials

  # look into `replica-set-persistent-volumes.yaml` for an example on how to use
  # Kubernetes Persistent Volumes in your MDB deployment.
  persistent: true

  # This will create a TLS enabled Replica Set, which means that all the traffic
  # between members of the Replica Set and clients, will be encrypted using TLS
  # certificates. These certificates will be generated on the fly by the operator
  # using the Kubernetes CA.
  # Please refer to Kubernetes TLS Documentation on how to approve these certs:
  #
  # https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
  #
  security:
    tls:
      enabled: true


