---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: product-service-2-mdb
spec:
  type: ReplicaSet

  members: 5
  version: 4.0.10

  project: configmap-opsmanager
  credentials: secret-opsmanager-credentials

  # look into `replica-set-persistent-volumes.yaml` for an example on how to use
  # Kubernetes Persistent Volumes in your MDB deployment.
  persistent: true

  #
  security:
    tls:
      enabled: true
    
    clusterAuthenticationMode: x509
    


