apiVersion: v1
kind: Secret
metadata:
  name: product-svc-mdbuser-pem
  namespace: mongodb
type: Opaque
data:
  pem: <Base 64 PEM>

stringData:
  uri: "mongodb+srv://product-service-2-mdb-svc.mongodb.svc.cluster.local"
  

